version: '3.8'

services:
  mongo:
    image: mongo:7
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./Backend
    container_name: backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - PORT=${PORT}
      - FRONTEND_ORIGIN=${FRONTEND_ORIGIN}
      - SESSION_SECRET=${SESSION_SECRET}
    depends_on:
      - mongo

  frontend:
    build: ./Frontend
    container_name: frontend
    restart: always
    ports:
      - "7456:7456"
    depends_on:
      - backend

volumes:
  mongo-data: